### ISSUE TITLE
does not appear to work on android

### ISSUE THREAD

**Issue by vonovak** [Flair-Dev/react-native-awesome-gallery#1]
Hello, thanks for the lib

I gave it a try on and ios and android (version 10) devices and I'd like to report that while it works nice on ios, it does not work on Android.

The issue can be reproduced with the readme sample.

On Android, double-tapping to zoom works, but swiping horizontally to change pictures does not work, and pinch to zoom does not work either. 

using RN 64 stable and reanimated 2

Maybe this should be mentioned in the readme. Thanks!

**Comment by pavelbabenko** [comment]
Hi @vonovak 
Thank you for your issue!
I've just fixed Android in v0.0.4 https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.0.4

**Comment by thienphuit** [comment]
Hi @pavelbabenko , i using android but not swip image when i using array, can i help me, fix it tks
