### ISSUE TITLE
Image snaps to horizontal center after scaling

### ISSUE THREAD

**Issue by yfunk** [Flair-Dev/react-native-awesome-gallery#13]
## Description
When performing any gesture to change the image scale, the image seems to always center itself horizontally after the gesture has ended. This is fine when scaling the image to be smaller than the container (`scale < 1`), but should not be happening when zooming in (`scale > 1`). 

Right now this causes the "focus" to shift away from the point that was zoomed into after ending the gesture. For me this issue is happening on Android using the package versions listed below, I was not yet able to test it on an iOS device.

https://user-images.githubusercontent.com/14955991/115701179-cf4fbb00-a367-11eb-938d-95cc112d5ba5.mp4

## Minimal code example
```ts
export const ImageScreen = () => {
  const source = 'https://homepages.cae.wisc.edu/~ece533/images/cat.png';
  return <Gallery data={[source]} />;
}
```

## Package versions
- `react-native`: 0.64.0
- `react-native-gesture-handler`: 1.10.3
- `react-native-reanimated`: 2.1.0
- `react-native-awesome-gallery`: 0.1.0 (also on 0.0.9)

**Comment by pavelbabenko** [comment]
Fixed in https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.1.1

**Comment by The-CodeNinja** [comment]
Facing the same issue. 
`react-native-awesome-gallery:` 0.3.5

```
<Gallery
 loop={true}
        emptySpaceWidth={0}
        style={{
          top: -57,
          position: 'absolute',
        }}
        onIndexChange={index => {
          setCurrentPage(index)
        }}
        ref={galleryRef}
        data={[...links]}
        renderItem={({ item }) => {
          return (
            <Pressable key={item.docID}>
                <Image
                  ...
                />
            </Pressable>
          )
        }}
        keyExtractor={(_item, index) => `${index}`}
      />
```

**Comment by krik-chry** [comment]
@pavelbabenko  Is this still an issue? I notice that when I zoom a lot it recenters the image, instead of staying in the place i stopped the gesture
