### ISSUE TITLE
Suggestion: disableTransitionOnScaledImage should not show adjacent images when enabled

### ISSUE THREAD

**Issue by ecklf** [Flair-Dev/react-native-awesome-gallery#16]
https://user-images.githubusercontent.com/8146736/120996893-0991e200-c787-11eb-8b2e-002011803b5c.mp4

**Comment by pavelbabenko** [comment]
Added `hideAdjacentImagesOnScaledImage` prop in [v0.1.6](https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.1.6)

**Comment by ecklf** [comment]
Super fast! Great job
