### ISSUE TITLE
Dynamically changed image data.

### ISSUE THREAD

**Issue by ZijianZhang991203** [Flair-Dev/react-native-awesome-gallery#19]
Hi, when I try to delete one of the image in the data array, I am still able to swipe to that index and it is black page. It froze then. I am guessing it is because the length of the array is not updated, any fix? Thanks!

**Comment by ZijianZhang991203** [comment]
If add one image in the array, it won't enable me to scroll to that. If delete one, it will still allow me to scroll to that page and freeze.

**Comment by pavelbabenko** [comment]
Hi @ZijianZhang991203
Fixed in [v0.1.7](https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.1.7)
