### ISSUE TITLE
RenderItem with FastImage failed

### ISSUE THREAD

**Issue by ZijianZhang991203** [Flair-Dev/react-native-awesome-gallery#20]
Here is my code:
`const customRenderImage = ({item, setImageDimensions}) => {
    return (
      <FastImage
        onLoad={e => {
          const {height: h, width: w} = e.nativeEvent.source;
          setImageDimensions({height: h, width: w});
        }}
        source={{uri: item.uri}}
        resizeMode={FastImage.resizeMode.contain}
        style={StyleSheet.absoluteFillObject}
      />
    );
  };`

My item looks like {
    key = "bf9e684f-495e-4427-b170-82504a006eb7",
    uri = "file://file:///Users/zijianzhang/Library/Developer/CoreSimulator/Devices/685BDAED-7EDA-4922-A082-56EA73788452/data/Containers/Data/Application/805F046E-2CAC-4C1B-9824-39B44CDB4EA3/tmp/IMG_0111.HEIC"}

Got error JSON value '{
    key = "bf9e684f-495e-4427-b170-82504a006eb7";
    uri = "file://file:///Users/zijianzhang/Library/Developer/CoreSimulator/Devices/685BDAED-7EDA-4922-A082-56EA73788452/data/Containers/Data/Application/805F046E-2CAC-4C1B-9824-39B44CDB4EA3/tmp/IMG_0111.HEIC";
}' of type NSMutableDictionary cannot be converted to NSString.

Even trying implement the same code as defaultRenderItem does not work and generate the same error. Is there anything I miss? Thank you!

**Comment by ZijianZhang991203** [comment]
I think renderItem prop is not working b/c I tried to change back my data into string array. It works again, and even with I changing renderItem props, it does nothing.

**Comment by pavelbabenko** [comment]
Hi @ZijianZhang991203 
I don’t think the issue is related to library. Please, check your data structure again and how do you use FastImage. If the issue still appears, add steps of how can I reproduce it and reopen the issue
