### ISSUE TITLE
Suggestion: Loop and onTap issue

### ISSUE THREAD

**Issue by valeriashpiner** [Flair-Dev/react-native-awesome-gallery#21]
Hello! 
Thank you for the great library @pavelbabenko!

I really like the code inside and whole functionality, it works perfectly.
I would like to know: Do you have the possibility to implement a loop in Gallery?
I think it will be a great addition. 

I also facing the issue when my single tap function calls even when I zoom in and zoom out. 
Probably because of conflict PinchGestureHandler and TapGestureHandler between each other.
Can it be two separate actions?

Thanks!

**Comment by pavelbabenko** [comment]
Hi @valeriashpiner 
Thank you for your suggestion and issue
I added `loop` prop and fixed tap in [v0.2.0](https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.2.0)
