### ISSUE TITLE
Bug: Pinch to zoom and move are not working together

### ISSUE THREAD

**Issue by valeriashpiner** [Flair-Dev/react-native-awesome-gallery#22]
**Platform**: iOS / Android
**Version of `react-native-awesome-gallery`:** 0.2.0
**Steps to reproduce:** Pinch to zoom with 2 fingers. Try to move/drag image with two fingers or one finger.
**Current behavour:** Image will centered in the middle all the time when I use `renderItem` prop, you can't move/drag it around while it zoomed. You can't view the top and bottom part of the image.
**Expected behavoir:** While zoomed in I can move the screen and view the top and bottom part of the image.

Thank you!

**Comment by pavelbabenko** [comment]
Hi @valeriashpiner 
Could you send me screen recording?
And code sample with gallery usage

**Comment by valeriashpiner** [comment]
@pavelbabenko I'll do it during few next hours! Thank you.

**Comment by valeriashpiner** [comment]
@pavelbabenko it works as intened if I don't use `renderItem` prop. As soon as I add `renderItem` prop and I send there some custom component this is happening.


```
import React from 'react';
import Gallery from 'react-native-awesome-gallery';
import { StyleSheet, Dimensions, Image } from 'react-native';

const images = [
  'https://upload.wikimedia.org/wikipedia/commons/c/cd/London_Montage_L.jpg',
  'https://assets.vogue.com/photos/58917ad38c64075803ad0876/master/pass/00-holding-first-timers-guide-to-london.jpg',
];

const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;

const renderSlideDeck = ({ item }) => {
  return <Image source={{ uri: item }} style={styles.image} />;
};

export default function App() {
  return (
    <Gallery
      data={images}
      renderItem={renderSlideDeck}
      onIndexChange={(newIndex) => {
        console.log(newIndex);
      }}
      loop={true}
    />
  );
}

const styles = StyleSheet.create({
  image: {
    width: width,
    height: height,
  },
});
```


https://user-images.githubusercontent.com/18754922/127513047-1c07f64a-9c1c-447e-b077-8fb92b2ca1be.MP4

**Comment by pavelbabenko** [comment]
As I see you’re using setImageDimensions incorrectly.
You have to pass width and height of loaded image, not dimensions of screen.
Please, check usage of setImageDimensions in example folder

**Comment by pavelbabenko** [comment]
If you have the same issue after using setImageDimensions properly, reopen the issue please

**Comment by valeriashpiner** [comment]
@pavelbabenko perfect, it works with right usage of setImageDimensions.
Sorry for that!
