### ISSUE TITLE
[Feature Request] Reset Transforms API

### ISSUE THREAD

**Issue by krnl-panic** [Flair-Dev/react-native-awesome-gallery#25]
Hi! Thanks for this library. It works very well within our project. I've had a few requests from our product team to enable support for resetting transforms (scale) when certain user events occur, such as an orientation change.

It would be extremely helpful if there was a ref API or other mechanism for resetting transforms on demand.

Thanks for taking a look!

**Comment by pavelbabenko** [comment]
Added `reset` method in [v0.2.2](https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.2.2)
