### ISSUE TITLE
Can not use pan gesture on tall images

### ISSUE THREAD

**Issue by Yusuf007R** [Flair-Dev/react-native-awesome-gallery#27]
you can not move up or down in really tall images,  its like the spring animation does not allow you to do. 

https://user-images.githubusercontent.com/45109516/131430966-e86a6c6e-e431-4c33-896d-ddd35aedcf78.mp4

**Comment by valeriashpiner** [comment]
We have the same bug.

**Comment by valeriashpiner** [comment]
@pavelbabenko we will appreciate, if you'll take a look :)

**Comment by pavelbabenko** [comment]
Fixed in [v0.2.3](https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.2.3)

**Comment by valeriashpiner** [comment]
@pavelbabenko when I try to zoom in to see the bottom of the image it keeps moving to the center a bit. Does zoom have any limitation with how much we can zoom in?

https://user-images.githubusercontent.com/18754922/134035570-a33750d7-0a5a-42b2-a5b0-cd2788e35dc0.MP4

**Comment by HeyItsJs** [comment]
I am facing the same issue (version: 0.3.6). Can we please reopen this issue?
