### ISSUE TITLE
onTap event is pretty slow

### ISSUE THREAD

**Issue by YassinEldeeb** [Flair-Dev/react-native-awesome-gallery#29]
onTap event takes about 2-4 seconds to fire.

![Record_2021-09--1631426676782](https://user-images.githubusercontent.com/72823042/132974139-48712102-3889-4310-902c-b010e669c5f7.gif)

sorry about the picture it's my dumb cat.

**Comment by pavelbabenko** [comment]
Hi @YassinEldeeb 
Thank you for your issue. 
Try to run the app in release mode and see if the issue still appears.
If you want to change the time interval between tap and double-tap, you can use `doubleTapInterval` prop which I added in [v0.2.5](https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.2.5)

**Comment by YassinEldeeb** [comment]
when I published my app to the Google Play Store it was 2x faster and it wasn't a problem anymore, but `doubleTapInterval` seems a good configuration if I faced any problems.

Thank you for clarifying it's not a performance issue but just the time to determine it's a tap or a Double Tap.
