### ISSUE TITLE
Bug: When zoom in on the long pic, tap while scrolling

### ISSUE THREAD

**Issue by alantoa** [Flair-Dev/react-native-awesome-gallery#33]
## Description
I'm binding onTap this method, when zoom in on the long pic, tap while scrolling, the onTap event is triggered by the scroll event.

### Code
```
<AwesomeGallery
    data={params?.images.map((uri) => ({ uri }))}
    keyExtractor={(_, i) => `${i}`}
    renderItem={({ index, item, setImageDimensions }) =>
      renderItem({ index, item, setImageDimensions })
    }
    initialIndex={params.index}
    onIndexChange={onIndexChange}
    onSwipeToClose={goBack}
    onTap={goBack}
  />
```

### Video demo:
https://user-images.githubusercontent.com/37520667/136947114-98d51f81-feb2-4e34-bb6f-b4aa833c68ec.MOV

### So we can ? & I hope 💗 :
    Turn off the onTap event in the scrool event?
    (or)
    Stop scrolling when tap?

## Thanks!!!



**Comment by pavelbabenko** [comment]
Fixed in [v0.3.1](https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.3.1)
