### ISSUE TITLE
Thank your for being a huge part of Memos

### ISSUE THREAD

**Issue by YassinEldeeb** [Flair-Dev/react-native-awesome-gallery#34]
there's no other way for contacting you @pavelbabenko
but I wanted to Thank you for being a very important part of memos which is a cloud storage for storing your best photos/videos, I started implementing the Gallery from scratch and after 4 days I slowly realized that It was a heavy task to handle gestures for swiping, zooming, pinching and momentum when moving while zooming all together without having huge performance issues. and that library was a really good abstraction that gave me the ability for adding other functionalities like time, share, set as album cover, delete, download and custom video player.

Links:
[Repo](https://github.com/YassinEldeeb/memos-app)
[Google Play Store](https://play.google.com/store/apps/details?id=com.yassineldeeb.memosapp)

**Comment by pavelbabenko** [comment]
Hi @YassinEldeeb 
I'm happy that you found the library helpful!
