### ISSUE TITLE
Update to new react-native-gesture-handler API?

### ISSUE THREAD

**Issue by 10000multiplier** [Flair-Dev/react-native-awesome-gallery#38]
Hi,

What an awesome component you've built!

I've noticed that the old API of `react-native-gesture-handler` is still being used.

Do you plan on updating to v2?

Thanks!

**Comment by MadeinFrance** [comment]
# I can't dismiss the photo screen.

This is my setup:

```
"react-native-gesture-handler": "^2.3.2",
"react-native-reanimated": "^2.4.1",
"@react-navigation/native": "^6.0.8",
"@react-navigation/stack": "^6.1.1",
"react-native-screens": "^3.13.1",
```

- Do you think it's related?

https://user-images.githubusercontent.com/1864359/159129944-36640920-71d2-437e-93a9-ea0ac06cc220.mov

**Comment by pavelbabenko** [comment]
@MadeinFrance Yes, it's related

**Comment by pavelbabenko** [comment]
RNGH v2 is now used in [v0.3.0](https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.3.0)
