### ISSUE TITLE
Buggy behavior while changing from portrait to landscape on zoomed in images

### ISSUE THREAD

**Issue by mtflud** [Flair-Dev/react-native-awesome-gallery#44]
While this is kind of hard to reproduce, it does happen. Looks like the library is having issues displaying an image after toggling between portrait and landscape while zoomed in. These are the reproduction steps that work consistently for me:

- Create a `react-native-awesome-gallery` component with 2 or more images
- Zoom in on an image and swipe to the other image while still zoomed in
- Zoom in on this new image
- Toggling between portrait and landscape
- Zoom out of the image
- Observe how images are overlapped

https://user-images.githubusercontent.com/2406654/174413776-90c32500-6054-46ca-8dc1-65bc165dc1bd.mov

Any help would be greatly appreciated!

**Comment by pavelbabenko** [comment]
@mtflud It’s too hard to save a right position with orientation change. I checked how native apps work and they reset scale too. So, I think the issue can be closed.
Reset function has a boolean parameter, which can animate resetting. Maybe it’ll make the orientation change smoother

**Comment by danielnedefo** [comment]
@mtflud hi dude,how you achieve this smoothly image resize on orientation change?
