### ISSUE TITLE
Does not work with a single image

### ISSUE THREAD

**Issue by Darkbladecr** [Flair-Dev/react-native-awesome-gallery#5]
When loading a Gallery with a single image, you are still able to swipe to a next image (which does not exist) and then breaks the navigator (unable to swipe back to the first and only image).

**Comment by Deain** [comment]
same issue

**Comment by pavelbabenko** [comment]
Fixed in https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.0.7
