### ISSUE TITLE
[Discussion] Library feedback

### ISSUE THREAD

**Issue by troZee** [Flair-Dev/react-native-awesome-gallery#7]
Hey @pavelbabenko 
Thank you for a great library. I am happy, that you are maintaining this library and I can use this library in my project. 
While I was developing, I noticed few things: 
- we can make a transition to the next item, once the image scale is greater than 1. I checked, how it looks like in the other apps (Twitter, WhatsApp, messenger )and the image scale needs to be 1 to go to the next page. When the image scale is greater than one (image is zoomed) it sticks to the edge (so offset is clamped to the 0, when the image touch the edge)

- it would be nice to have a prop, which could block a vertical gesture when the scale of the image is 1 (when an image is not resized). I did it locally in my project so I could make a PR for that feature. Before I do it, please let me know, if you would like to handle it in your library. 

- I also implemented `setPage` locally and it looks like below : 
```js 
    useImperativeHandle(ref, () => ({
      setPage(index: number) {
        setIndex(index);
        currentIndex.value = index;
        translateX.value = index * -(dimensions.width + emptySpaceWidth);
      },
    }));
```
ant then you can use it as follow: 
`galleryRef.current.setPage(index);`

And I am not sure if it is a good solution. I was trying to move the below code to the parent component
```js
const [index, setIndex] = useState(initialIndex);
 ```
But it did not work very well. Also, It would be nice to have this kind of functionality inside the library 

WDYT about my propositions ?

**Comment by pavelbabenko** [comment]
Hi @troZee 

Thanks for you suggestions.

1. I copied functionality from Telegram messenger, but I'll add a prop to disable transition to next when scale is bigger than 1.
2. Feel free to create PR with features you'd like to have. I want to build a complex toolkit to cover a lot of cases, so I'm opened to new ideas.
3. I've added useState to implement maxNumToRender prop. I don't think there is a better place for it.

**Comment by troZee** [comment]
> Hi @troZee
> 
> Thanks for you suggestions.
> 
> 1. I copied functionality from Telegram messenger, but I'll add a prop to disable transition to next when scale is bigger than 1.
> 2. Feel free to create PR with features you'd like to have. I want to build a complex toolkit to cover a lot of cases, so I'm opened to new ideas.
> 3. I've added useState to implement maxNumToRender prop. I don't think there is a better place for it.

Ad. 1 What a good news :D ❤️  cant wait 
Ad.2 I will prepare a pull request with suggested changes (Then we can discuss about it in the PR)

Thank you for discussion. I am closing this topic, bc everything is clear for me.

**Comment by pavelbabenko** [comment]
@troZee 
`disableTransitionOnScaledImage ` prop is added in https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.0.9

**Comment by troZee** [comment]
> @troZee 
> `disableTransitionOnScaledImage ` prop is added in https://github.com/Flair-Dev/react-native-awesome-gallery/releases/tag/v0.0.9

Wooow you are so fast ❤️ thank you so much. I really appreciate it 🥰
